name: Docker

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        dockerfile: ['python2', 'python3']
    steps:
      - uses: actions/checkout@v1
      - name: login
        run: |
          docker login docker.pkg.github.com -u github -p $TOKEN
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t panda3d:latest -f ${{ matrix.dockerfile }}.Dockerfile .
      - name: tag and push
        run: |
          image=docker.pkg.github.com/judge2020/panda3d/panda3d-${{ matrix.dockerfile }}
          docker tag panda3d:latest $image:${GITHUB_SHA:0:20}
          docker tag panda3d:latest $image:$(date +%s)
          docker tag panda3d:latest $image:latest
          docker push $image
